"""todos table

Revision ID: 845c2e7c9408
Revises: f661954d6b71
Create Date: 2023-12-31 12:52:18.751706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845c2e7c9408'
down_revision = 'f661954d6b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('content', sa.String(length=140), nullable=False),
    sa.Column('complete', sa.String(length=140), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todo_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_user_id'))

    op.drop_table('todo')
    # ### end Alembic commands ###
