"""new fields in user model

Revision ID: 973aa02824d8
Revises: 845c2e7c9408
Create Date: 2023-12-31 13:30:44.194576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973aa02824d8'
down_revision = '845c2e7c9408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
